---

apiVersion: v1
kind: Pod
metadata:
  name: shared-namespace
spec:
  shareProcessNamespace: true
  containers:
  - name: go-app
    image: trivial-webserver
    imagePullPolicy: Never
  - name: shell
    image: busybox:1.28
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
    stdin: true
    tty: true
